### ISSUE TITLE
WMTS Application example needs clarifications

### ISSUE THREAD

**Issue by fnicollet** [Melown/workshop#15]
Hello,

The WMTS example (http://melown.readthedocs.io/en/latest/clients/javascript/wmts-example.html#wmts-app) has a few typos ("You as shown in the WMTS Application example examle," ...) and it seems to be missing some parts? 

Like for instance, you configure the Proxy/ProxyPass (not sure why it says /melown/ and /melown2015/ right after, maybe a typo?) so that there is no CORS issue when the browser will be loading the image, but at what point do you specify the WMTS service you want to add (its URL)?

The URLs in the documentation all point to a mapConfig JSON on "localhost", so you can't really inspect when has been added there. I guess you would need to add a ressource, and there should be a "wmts" driver instead of "tms", but an example would be appreciated

Globally, most examples on readthedocs point to localhost, so it is not really helpful, as you would expect the online documentation to point to a demo server or something.

Thanks,

**Comment by jachym** [comment]
Hi,

yes, most of the exsamples are pointing to localhost - they are written in a way, that you can all do it at your  local machine "from scratch".  

`/melown/` and `/melown2015/` is not a typo, server will redirect from `group name` to `reference frame`
Since the WMTS serverice is  proxyed with `mapproxy` service on the server, and it's configuration is served as part of  the `mapConfig.json` file. 

The resource is `tms` - for whatever reason, that's how it is. Even when the service is `WMTS` - `mapproxy` uses GDAL for reading anyway.  Example of how to get it configured is in http://melown.readthedocs.io/en/latest/server/mapproxy/examples/au-cz.html#srtm-example

Demo server would be nice, I agree, we need to talk about this option. But the docs are, as already metioned, created for your local machine.

I'm creating new ticket #18, which covers this.

Feel free to re-open this ticket, if I did not address some of your questions.

Thanks  @fnicollet
